/** Amazon Fulfillment Center codes mapped to US states.
 *  Covers FCs, sort centers, and delivery stations (S-prefix).
 *  Last updated: 2026-09-02
 */
const FC_CODES: Record<string, string> = {
  ABE2: "NJ", ABE3: "NJ", ABE4: "NJ", ABE8: "NJ",
  ABQ1: "NM", ABQ2: "NM",
  ACY1: "NJ", ACY2: "NJ", ACY5: "NJ",
  AFW1: "TX",
  AGS1: "GA", AGS5: "GA",
  AKC1: "OH",
  ALB1: "NY",
  ATL6: "GA", ATL7: "GA", ATL8: "GA",
  AUS2: "TX", AUS3: "TX",
  AVP1: "PA", AVP2: "PA", AVP3: "PA", AVP6: "PA",
  BDL1: "CT", BDL2: "CT", BDL3: "CT",
  BDU2: "CO",
  BFI1: "WA", BFI3: "WA", BFI4: "WA", BFI5: "WA",
  BFL1: "CA", BFL2: "CA",
  BHM1: "AL",
  BJC1: "CO",
  BKY1: "KY",
  BNA2: "TN", BNA3: "TN", BNA5: "TN", BNA6: "TN",
  BOI2: "ID",
  BOS7: "MA",
  BTR1: "LA",
  BWI2: "MD", BWI4: "MD", BWI5: "MD",
  CAE1: "SC",
  CHA1: "TN", CHA2: "TN",
  CHO1: "VA",
  CLE2: "OH", CLE3: "OH", CLE5: "OH",
  CLT2: "NC", CLT3: "NC", CLT5: "NC",
  CMH1: "OH", CMH2: "OH", CMH3: "OH", CMH4: "OH",
  CSG1: "GA",
  CVG1: "KY", CVG2: "KY", CVG3: "KY", CVG5: "KY",
  DAB2: "FL",
  DAL2: "TX", DAL3: "TX",
  DCA1: "VA", DCA6: "VA",
  DEN2: "CO", DEN3: "CO", DEN5: "CO", DEN8: "CO",
  DET3: "MI", DET6: "MI",
  DFW6: "TX", DFW7: "TX", DFW8: "TX",
  DSM5: "IA",
  DTW1: "MI", DTW5: "MI",
  ELP1: "TX",
  EWR4: "NJ", EWR5: "NJ", EWR7: "NJ", EWR9: "NJ",
  FAR1: "ND",
  FAT1: "CA", FAT2: "CA",
  FSD1: "SD",
  FTW1: "TX", FTW2: "TX", FTW4: "TX", FTW6: "TX",
  FWA4: "IN", FWA6: "IN",
  GEG1: "WA", GEG2: "WA",
  GRR1: "MI",
  GSP1: "SC",
  GYR1: "AZ", GYR2: "AZ", GYR3: "AZ",
  HGR5: "MD",
  HIA1: "FL",
  HOU1: "TX", HOU2: "TX", HOU3: "TX", HOU7: "TX",
  IAD1: "VA",
  IAH1: "TX", IAH3: "TX",
  ICT2: "KS",
  IGA3: "GA",
  IGQ1: "IL",
  ILM1: "NC",
  IMO1: "MO",
  IND1: "IN", IND2: "IN", IND3: "IN", IND4: "IN", IND5: "IN", IND9: "IN",
  ITX3: "TX",
  IWA6: "WA",
  JAN1: "MS",
  JAX2: "FL", JAX3: "FL", JAX5: "FL",
  JFK8: "NY",
  JHW1: "NY",
  JVL1: "WI",
  KRB1: "TX", KRB2: "TX", KRB4: "TX",
  LAN2: "MI",
  LAS1: "NV", LAS2: "NV", LAS6: "NV", LAS7: "NV",
  LAX9: "CA",
  LBE1: "PA",
  LEX1: "KY", LEX2: "KY",
  LGA7: "NJ", LGA9: "NJ",
  LGB3: "CA", LGB4: "CA", LGB6: "CA", LGB8: "CA",
  LIT1: "AR", LIT2: "AR",
  LUK2: "OH",
  MCC1: "CA",
  MCI1: "KS", MCI5: "KS",
  MCO1: "FL", MCO2: "FL", MCO5: "FL",
  MDT1: "PA", MDT2: "PA", MDT6: "PA",
  MDW2: "IL", MDW4: "IL", MDW6: "IL", MDW7: "IL",
  MEM1: "TN", MEM4: "TN", MEM5: "TN", MEM6: "TN",
  MGE3: "GA",
  MIA1: "FL", MIA5: "FL",
  MKC6: "MO",
  MKE1: "WI", MKE2: "WI", MKE5: "WI", MKE6: "WI",
  MLI1: "IL",
  MMU1: "NJ",
  MQY1: "TN",
  MSP1: "MN", MSP4: "MN",
  MSY1: "LA",
  MTN1: "MD",
  OAK3: "CA", OAK4: "CA", OAK5: "CA",
  OKC1: "OK",
  OMA2: "NE",
  ONT2: "CA", ONT5: "CA", ONT6: "CA", ONT8: "CA", ONT9: "CA",
  ORD2: "IL", ORD9: "IL",
  ORF2: "VA",
  ORH3: "MA",
  OXR1: "CA",
  PAE2: "WA",
  PBI3: "FL",
  PCW1: "OH",
  PDX7: "OR", PDX9: "OR",
  PGA1: "AZ",
  PHL4: "PA", PHL5: "PA", PHL6: "PA", PHL7: "PA",
  PHX3: "AZ", PHX5: "AZ", PHX6: "AZ", PHX7: "AZ",
  PIT2: "PA",
  PSP1: "CA", PSP3: "CA",
  PVD2: "RI",
  RDG1: "PA",
  RDU1: "NC",
  RFD2: "IL",
  RIC1: "VA", RIC2: "VA", RIC3: "VA",
  RNO4: "NV",
  ROC1: "NY",
  RYY2: "GA",
  SAH1: "TX",
  SAN3: "CA",
  SAT1: "TX", SAT2: "TX", SAT4: "TX",
  SAV3: "GA", SAV5: "GA",
  SAX1: "CA", SAX2: "CA", SAX3: "CA", SAX5: "CA", SAX6: "CA", SAX7: "CA",
  SAZ1: "AZ", SAZ2: "AZ", SAZ3: "AZ",
  SBD1: "CA", SBD2: "CA",
  SBN1: "IN",
  SCA4: "CA", SCA5: "CA", SCA7: "CA",
  SCK4: "CA",
  SCO1: "CO", SCO2: "CO",
  SDF1: "KY", SDF2: "KY", SDF4: "KY", SDF6: "KY", SDF8: "KY", SDF9: "KY",
  SDM4: "CA",
  SEA6: "WA", SEA8: "WA",
  SFL1: "FL", SFL2: "FL", SFL3: "FL", SFL4: "FL", SFL6: "FL", SFL7: "FL", SFL8: "FL",
  SGA1: "GA", SGA2: "GA",
  SHV1: "LA",
  SIA2: "IA",
  SID1: "ID",
  SIL1: "IL", SIL2: "IL", SIL3: "IL", SIL4: "IL",
  SIN9: "IN",
  SJC7: "CA",
  SKY2: "KY",
  SLC1: "UT",
  SMA1: "MA", SMA2: "MA",
  SMD1: "MD",
  SMF1: "CA", SMF3: "CA", SMF6: "CA",
  SMI1: "MI",
  SMN1: "MN",
  SMO1: "MO", SMO2: "MO",
  SNA4: "CA",
  SNC2: "NC", SNC3: "NC", SNC6: "NC",
  SNE1: "NE",
  SNJ1: "NJ", SNJ2: "NJ", SNJ3: "NJ",
  SNV1: "NV",
  SNY1: "NY", SNY2: "NY", SNY5: "NY",
  SOH1: "OH", SOH2: "OH", SOH3: "OH",
  SOK1: "OK",
  SOR3: "OR",
  SPA1: "PA", SPA4: "PA", SPA5: "PA",
  SSC4: "SC",
  STL3: "MO", STL4: "MO", STL8: "MO",
  SWF1: "NY",
  TEB3: "NJ", TEB4: "NJ", TEB6: "NJ", TEB9: "NJ",
  TFC1: "CT",
  TPA1: "FL", TPA2: "FL",
  TUL1: "OK", TUL2: "OK",
  TUS1: "AZ", TUS2: "AZ",
};

export function fcToState(fcCode: string): string | null {
  const code = fcCode.trim().toUpperCase();
  if (FC_CODES[code]) return FC_CODES[code];
  // Try prefix match (strip trailing digits)
  const prefix = code.replace(/\d+$/, "");
  for (const [k, v] of Object.entries(FC_CODES)) {
    if (k.startsWith(prefix)) return v;
  }
  return null;
}
